### PR TITLE
A workaround for when you want to repeat monthly but start outside the bounds of other months (i.e. 29th, 30th and 31st)

### PR DESCRIPTION
**Pull request by pospi**
added the ability to automatically pull back repeating month intervals to the end of the month when date offsets exceed it

### CODE REVIEW

**Comment by MattiJarvinen** [comment]
Btw. Google Calendar skips recurring event if day of month > days in month.

For example monthly repeat for 31st day does not occur at all in months with fewer days. I don't know if that is correct or not.

**Comment by PrplHaz4** [comment]
We have implemented When and forced behavior similar to what @pospi has implemented here...it's definitely a problem that exists in the real world.

Also, the Carbon guys are having a similar discussion here:
https://github.com/briannesbitt/Carbon/issues/236

**Comment by perochak** [comment]
If the date is last date of the month then for the next event, it should be the last date of the coming month.
I have face same issue with monthly events and figured out. see  #61

**Comment by boryn** [comment]
Hi @pospi! I was looking at your fork of the library and found this branch https://github.com/pospi/When/tree/all-custom-extensions. Does it include all your improvements to the main library? Though I can see the that this branch "is 64 commits behind tplaner:master." Could you make a merge with the main master along with your improvements so that we can use the best version of the library?

**Comment by tplaner** [comment]
I've pulled this into the master branch. Thanks for your contribution.

**Comment by boryn** [comment]
Thank you @tplaner! Would you make a new release with the fresh changes? Installing through `composer require tplaner/When` grabs 3.0.0 version.

**Comment by tplaner** [comment]
Done: https://github.com/tplaner/when/tree/v3.1.0

**Pull request closed without merging**
